Add no-dependency initial check for Bash version

diff --git a/bin/doctor b/bin/doctor
--- a/bin/doctor
+++ b/bin/doctor
@@ -1,4 +1,13 @@
 #!/usr/bin/env bash
+
+# This is a no-dependency initial check to fail early in case Bash is too old,
+# because if it is there'll just be cryptic errors when sourcing .shhelpers.
+if [ "${BASH_VERSINFO:-0}" -lt 4 ]; then
+  echo -e "• Check Bash version ✗"
+  echo -e "Suggested remedy: source bin/bootstrap"
+  exit 1
+fi
+
 set -euo pipefail
 
 source "$(dirname "$0")/.shhelpers"
